### PR TITLE
Changed korean female voice to the current updated version Papago uses

### PR DESCRIPTION
**Pull request by acottis**
The old Korean voice is robotic and the new one sounds much more natural. Found the voice from the website request URL when you press play "https://papago.naver.com/apis/tts/c_lt_6690-nvoice_kyuri_2.0.3_fc8d515a6e1d3f026161ce5b0343603b-1594486095707"

### CODE REVIEW

**Comment by scottgigante** [comment]
Thanks for the PR! Test is failing for an unrelated reason which has been fixed on master -- do you mind updating the branch to check that the tests now pass?

**Review by acottis — COMMENTED** [review]
Trying to commit again

**Comment by scottgigante** [comment]
Merging. Thanks again!

**Comment by acottis** [comment]
No problem, I really found this code super helpful for my project.

Thank you,
Adam

**Pull request merged**
